### ISSUE TITLE
Can't change icon colors

### ISSUE THREAD

**Issue by nsrosenqvist** [archilex/filament-toggle-icon-column#33]
I've tried using different ways of defining it, setting the Filament color name (ie. 'danger') and using the `Color` enum. The icon shows, and if I leave the defaults then the colors work, but as soon as I set something else it is just black (dark grey or whatever the default is in Filament). Please advise.

**Comment by nsrosenqvist** [comment]
I'm also curious if there is a way one can trigger an action along with toggling the state, e.g. for opening a modal where one can add a note to explain why the state has been set.

**Comment by archilex** [comment]
@nsrosenqvist Sorry for the late response. It's been a busy month. You are correct that out of the box, using a different color is no longer supported as of Filament v3 due to the way Filament is handling custom colors. 

I looked into updating the plugin to implement Filamen't color system today, but unfortunately it doesn't easily (maybe not at all) allow different colors to be used for normal state and hover state. You can use different SHADES of the same color, but for this plugin, the hover color is usually a completely different color than the current state color and that doesn't seem to be possible with Filament's color system.

Because of this, I'm going to update the docs to require using a custom theme if you want to change the default colors. The steps to do that are in the readme in this github page. I'll have to submit a plugin update for them to be reflected on Filament's site.

There might be a way to work around this and implement my own color system, but asking devs to do a custom theme is trivial, and only one other person has brought this up, so a custom theme is the route I'm going to take for now.

**Comment by archilex** [comment]
> I'm also curious if there is a way one can trigger an action along with toggling the state, e.g. for opening a modal where one can add a note to explain why the state has been set.

As for calling an action, while editable columns (like ToggleColumn, TextInputColumn), can't use the `->action()` method  like other table columns, you can use `afterStateUpdated()` to do something afterwards.

**Comment by nsrosenqvist** [comment]
@archilex I see, thanks for the explanation! I'll see what I can do then, and maybe I'll have to make something custom to support everything I have in mind anyway. Thanks!
